magus/react-native-facebook-login

README.md

A simple oversight, but potentially confusing to a n00b.

added #import statement to readme

---

RCTFBLogin/RCTFBLoginManager.m

Invoke RCTFBLoginManager on main thread

---

README.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/38)

chore: add android setup link to readme

---

README.md

Just a typo fix.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/56)

Fixes name of libRCTFBLogin.a

---

android/src/main/java/com/magus/fblogin/FacebookLoginModule.java

When trying to use token expiration date from android in momentjs, got this warning: https://github.com/moment/moment/issues/1407
This is my attempt to fix this problem.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/63)

Changing token expiration date format to ISO

---

Android.md
android/build.gradle
android/src/main/java/com/magus/fblogin/FacebookLoginModule.java
android/src/main/java/com/magus/fblogin/FacebookLoginPackage.java

NOTE: I've not tested this. But I've been using similar module in prod.

Refactor Facebook login

---

index.android.js

I added logout method for end Facebook Session from external (neceesary when you have other login forms). 
It's only implemented for Android library.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/98)

Logout methd to end session from external

---

README.md
android/README.md
example/components/Login.js
example/components/LoginMock.js
index.android.js
index.ios.js
package.json

Instead of 
```js
var {NativeModules} = require('react-native');
var FBLogin = require('react-native-facebook-login');
var FBLoginManager = NativeModules.FBLoginManager;
```
Now just one line
```js
var {FBLogin, FBLoginManager} = require('react-native-facebook-login');
```
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/114)

chore: consolidate imports for module

---

index.android.js
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/120)

chore: use itypeof module

---

android/src/main/java/com/magus/fblogin/FacebookLoginModule.java

fixes https://github.com/magus/react-native-facebook-login/issues/131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/132)

support RN 0.30.0

---

index.android.js

- add buttonText as prop to FBLogin to customise own text
- fix fontStyle where props was missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/135)

Custom Button Text and fontStyle fix 

---

README.md

I copied this example and i got burned bad by this! Please accept PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/136)

fix small mistake example

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/138)

chore: update readme example

---

index.android.js
index.ios.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/142)

fix: undefined self var

---

android/src/main/java/com/magus/fblogin/FacebookLoginModule.java
index.android.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/156)

chore: namespace android FBLoginManager to MFBLoginManager

---

android/src/main/java/com/magus/fblogin/FacebookLoginModule.java

should resolve #158 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/159)

add missing android method

---

index.android.js
index.ios.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/162)

fix: unexpected token

---

android/src/main/java/com/magus/fblogin/FacebookLoginModule.java
index.android.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/165)

fix: refactor getCredentials method to align with ios

---

android/README.md
android/build.gradle
android/src/main/java/com/magus/fblogin/FacebookLoginModule.java
index.android.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/170)

chore(android): update fbsdk to 4.16

---

android/README.md
android/src/main/java/com/magus/fblogin/FacebookLoginModule.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/173)

fix(android): add missing import

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/184)

include npm version in README

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/188)

Make setup point more clear.

---

RCTFBLogin/RCTFBLogin.h
RCTFBLogin/RCTFBLogin.m
RCTFBLogin/RCTFBLoginManager.h
RCTFBLogin/RCTFBLoginManager.m

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/196)

Support for RN 0.40.0

---

index.android.js

By pass the prop onClickColor to the Login component, you can set the underlayColor Color.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/210)

Added the ability to set the 'underlayColor' of the login button

---

index.android.js
index.ios.js

Fixed this issue for FBLogin
https://github.com/magus/react-native-facebook-login/pull/35
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/magus/react-native-facebook-login/183)

Fixed setState after FBLogin unmount (ios+android)

---

index.ios.js

Please pull. Breaking change in Production for ios builds

Update ViewPropTypes style in index.ios.js

---

RCTFBLogin/RCTFBLogin.m
RCTFBLogin/RCTFBLoginManager.m
README.md
react-native-facebook-login.podspec

With the file new RN auto-linking system will add needed dependencies to podfile and compile. No manual installation needed.

Added podspec file for RN 0.60 compatibility
